version: '3'
services:
  core-api:
    build: CoreApi\.
    ports:
     - "5000:5000"
  ui:
    build: UI\.
    ports:
     - "80:80"
    depends_on:
     - "core-api"
  helloworld:
    build: Plugins\HelloWorld\.
    ports:
     - "5001:5001"
    depends_on:
     - "core-api"
    environment:
     - PYTHONUNBUFFERED=0